### ISSUE TITLE
Julia type hierachy as an example for creating a tree

### ISSUE THREAD

**Issue by scls19fr** [JuliaCollections/AbstractTrees.jl#20]
Hello,

Following https://github.com/JuliaLang/julia/issues/24741#issuecomment-414212785
maybe `AbstractTrees` could provide an example to get a tree of type hierarchy.

Kind regards

**Comment by FedeClaudi** [comment]
A bit late to the party here, but [Term](https://github.com/FedeClaudi/Term.jl) now provides functionality very much like the one discussed above, see [here]: https://fedeclaudi.github.io/Term.jl/stable/ren/tree/#TypeTree

<img width="336" alt="image" src="https://user-images.githubusercontent.com/17436313/161416483-a424a8a8-babb-42bf-b6d7-13d4cd1c5bf6.png">

**Comment by scls19fr** [comment]
As suggested by @karlwessel in https://github.com/JuliaLang/julia/issues/24741#issuecomment-496212498

```julia
julia> AbstractTrees.children(x::Type) = subtypes(x)

julia> print_tree(Number)
Number
├─ Complex
└─ Real
   ├─ AbstractFloat
   │  ├─ BigFloat
   │  ├─ Float16
   │  ├─ Float32
   │  └─ Float64
   ├─ AbstractIrrational
   │  └─ Irrational
   ├─ Integer
   │  ├─ Bool
   │  ├─ Signed
   │  │  ├─ BigInt
   │  │  ├─ Int128
   │  │  ├─ Int16
   │  │  ├─ Int32
   │  │  ├─ Int64
   │  │  └─ Int8
   │  └─ Unsigned
   │     ├─ UInt128
   │     ├─ UInt16
   │     ├─ UInt32
   │     ├─ UInt64
   │     └─ UInt8
   └─ Rational
```
