### ISSUE TITLE
Empty array has children?

### ISSUE THREAD

**Issue by joshday** [JuliaCollections/AbstractTrees.jl#49]
Is this an intentional change?  

Previously, dots would not appear when the depth landed on a node that was an empty array.

```julia
julia> print_tree([[1,2],[]], 2)
Array{Array{Any,1},1}
├─ Array{Any,1}
│  ├─ 1
│  └─ 2
└─ Array{Any,1}

julia> print_tree([[1,2],[]], 1)
Array{Array{Any,1},1}
├─ Array{Any,1}
│  ⋮
│  
└─ Array{Any,1}
   ⋮
```

**Comment by jlumpe** [comment]
Not sure when it was fixed, but this is no longer happening in the current release (0.3.4).
