### ISSUE TITLE
API for lazy child access

### ISSUE THREAD

**Issue by jlumpe** [JuliaCollections/AbstractTrees.jl#60]
It's probably safe to say that most implementations of `children()` are "eager" in that they return some kind of explicit collection type like an Array. This has no performance cost when this collection is already stored as one of the node's attributes, but may be non-negligible if this collection has to be constructed with each call. Simpler queries about a node's children that do not require getting the full set, such as just counting their number, will incur a lot of unnecessary overhead in this case if we can only rely on the return value of `children()` (like `length(children(node))`).

I'd like this package to both include some efficient implementations of generic tree algorithms as well as support the easy creation of new ones, which would require adding some additional functions to the public API to support these cases. There are already a few undocumented examples scattered around the source code:

* `has_children(node)` - checks whether an object has any children at all, although the implementation is broken (see #56).
* `nodetype(::Type)` - type trait for expected value of `eltype(children(node))`.
* `getnode(node, ...)` - get a specific node based on its index, if applicable? There's some kind of notion of indexed trees which could be useful but isn't really documented.
* `childindices(node)` - get the node's child indices.
* `idxtype(node)` - I'm guessing the expected value of `eltype(childindices(node))`.

In addition to these I think it's important to at least have an `nchildren(node)` function, although I can envision others.

I'm planning on submitting a PR for this myself but would like to solicit some feedback on the design first. If this extended version of the API gets defined and documented then a lot more useful algorithms and utilities could be added to this package.

**Comment by jlumpe** [comment]
Another thought - all the functions mentioned above correspond to existing functions in `Base` which operate on generic collections. I wonder if it might make sense to define a type which lazily implements a collection of a node's children:

```
struct Children{N}
    node::N
end
```

Instead of defining a lot of new functions specific to `AbstractTrees`, we can implement the API for a node type `N` by overriding the following `Base` methods for `Children{N}`:

* `nchildren(node)` -> `Base.length(Children(node))`
* `nodetype(N::Type)` -> `Base.eltype(::Type{Children{N}}) where N`
* `idxtype(N::Type)` -> `Base.keytype(::Type{Children{N}}) where N`
* `getnode(node::N, i...)` -> `Base.getindex(c::Children{N}, i...)`
* `childindices(node::N)` -> `Base.keys(c::Children{N})`

It would be important to for this to be compatible with implementations which just use `children()`, though.

**Comment by jlumpe** [comment]
@Keno @timholy would love to get your thoughts on the best design for this API.

**Comment by timholy** [comment]
I don't have a lot to say, I'm afraid, beyond what's in https://github.com/JuliaCollections/AbstractTrees.jl/blob/master/examples/binarytree_infer.jl. It would be nice to make that a bit simpler. Certainly having a couple of examples might help.

**Comment by jlumpe** [comment]
@ExpandingMan @oscardssmith I think this has been resolved more or less by the latest set of changes?
