### ISSUE TITLE
Core.Compiler.Timings tests failing on nightly

### ISSUE THREAD

**Issue by jlumpe** [JuliaCollections/AbstractTrees.jl#71]
[Most recent build](https://github.com/JuliaCollections/AbstractTrees.jl/actions/runs/597096421) failing on Julia nightly.

Unrelated, but I noticed a potential issue in the following [line](https://github.com/JuliaCollections/AbstractTrees.jl/blob/b421a1dd6c525a4614acd130762eb91097ba117f/src/builtins.jl#L31):

```
printnode(io::IO, t::Core.Compiler.Timings.Timing) = print(io, t.time/10^6, "ms: ", t.mi_info)
```

I'm assuming `t.time` is in seconds, so it should either be `/10^3` and "ms" or `/10^6` and "ns".

**Comment by timholy** [comment]
Thanks for pointing it out. Fixed in #72.

> I'm assuming t.time is in seconds

That would be a good guess, but it's actually from the equivalent of `time_ns()`. (Fun fact: `Core.Compiler` doesn't even know how to handle floating-point numbers, everything is integer arithmetic.)
