### ISSUE TITLE
[FR] Implementation of a breadth-first iterator

### ISSUE THREAD

**Issue by theogf** [JuliaCollections/AbstractTrees.jl#75]
Would it be possible to add an implementation of a [breadth-first iterator](https://en.wikipedia.org/wiki/Tree_traversal#Breadth-first_search,_or_level_order) ?
Or is that not possible in a generic way?

**Comment by timholy** [comment]
You know about https://juliacollections.github.io/AbstractTrees.jl/stable/api/#AbstractTrees.StatelessBFS? But if you need a more efficient option, I'd encourage you to give it a try and see if you can contribute it.

**Comment by theogf** [comment]
I completely missed it :flushed: and I just ended up implementing a statefull BFS.
Very sorry for the noise!

**Comment by timholy** [comment]
If it's generic, consider contributing it here. I doubt you'll be the last to ask.
